sudo: required

language: ruby

services:
  - docker

env:
  - TARGET_CONTAINER_ID=container-php-emacs

before_script:
  - docker build -t php-emacs .
  - docker run -d --name $TARGET_CONTAINER_ID php-emacs

rvm:
  - 2.0.0

before_install:
  - gem update bundler

script:
  - bundle exec rake spec

cache: bundler
